#!/bin/bash

# Sudo check
if [ "$EUID" -ne 0 ] ; then
 printf '
  Please make sure you start dripe with sudo or as root (required for file permissions).
  This requires dripe to be placed in or symlinked to /usr/local/bin/dripe with chmod a+x.
  --- Dripe quits now. ---\n\n'
 exit
fi

read -p "Make sure you are in a drupal root (y/n):" YN
if [[ "$YN" == "y" ]] ; then
  
  # repair file and folder permissions
  read -p "We usually use www-data for group but which user is the owner?
  Press <enter> to keep yourself (default), or type carefully another users machine name: " NEWUSER
  if [ -z "${NEWUSER}" ] ; then
    NEWUSER=$USER
  fi
  chown -R $NEWUSER:www-data .
  find . -type d -exec chmod u=rwx,g=rx,o= '{}' \;
  find . -type f -exec chmod u=rw,g=r,o= '{}' \;
  chmod -R ug=rwx,o= sites/default/files
  chmod 440 sites/default/settings.php
  
  # Clean Drupal root from README.txt and alike files
  find . -type f -name "README.*" -exec rm '{}' \;
  find . -type f -name "COPYRIGHT.*" -exec rm '{}' \;
  find . -type f -name "INSTALL.*.txt" -exec rm '{}' \;
  find . -type f -name "MAINTAINER*" -exec rm '{}' \;
  find . -type f -name "UPGRADE.txt" -exec rm '{}' \;
  find . -type f -name "CHANGELOG.*" -exec rm '{}' \;
  find . -type f -name "LICENSE.*" -exec rm '{}' \;
  
else
  printf "\nOk. I stop and quit.\n"
fi
